# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loan_manage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='loan_manage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11loan_manage.proto\"\x1c\n\x0bUserDetails\x12\r\n\x05\x65mail\x18\x01 \x01(\t29\n\x0fSaveLoanService\x12&\n\x08SaveLoan\x12\x0c.UserDetails\x1a\x0c.UserDetailsb\x06proto3'
)




_USERDETAILS = _descriptor.Descriptor(
  name='UserDetails',
  full_name='UserDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='UserDetails.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=49,
)

DESCRIPTOR.message_types_by_name['UserDetails'] = _USERDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserDetails = _reflection.GeneratedProtocolMessageType('UserDetails', (_message.Message,), {
  'DESCRIPTOR' : _USERDETAILS,
  '__module__' : 'loan_manage_pb2'
  # @@protoc_insertion_point(class_scope:UserDetails)
  })
_sym_db.RegisterMessage(UserDetails)



_SAVELOANSERVICE = _descriptor.ServiceDescriptor(
  name='SaveLoanService',
  full_name='SaveLoanService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=51,
  serialized_end=108,
  methods=[
  _descriptor.MethodDescriptor(
    name='SaveLoan',
    full_name='SaveLoanService.SaveLoan',
    index=0,
    containing_service=None,
    input_type=_USERDETAILS,
    output_type=_USERDETAILS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAVELOANSERVICE)

DESCRIPTOR.services_by_name['SaveLoanService'] = _SAVELOANSERVICE

# @@protoc_insertion_point(module_scope)
