# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import loan_manage_pb2 as loan__manage__pb2


class SaveLoanServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveLoan = channel.unary_unary(
                '/SaveLoanService/SaveLoan',
                request_serializer=loan__manage__pb2.UserDetails.SerializeToString,
                response_deserializer=loan__manage__pb2.UserDetails.FromString,
                )


class SaveLoanServiceServicer(object):
    """Service definition
    """

    def SaveLoan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SaveLoanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveLoan,
                    request_deserializer=loan__manage__pb2.UserDetails.FromString,
                    response_serializer=loan__manage__pb2.UserDetails.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SaveLoanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SaveLoanService(object):
    """Service definition
    """

    @staticmethod
    def SaveLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SaveLoanService/SaveLoan',
            loan__manage__pb2.UserDetails.SerializeToString,
            loan__manage__pb2.UserDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
